services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minioadmin miniopassword;
      /usr/bin/mc rm -r --force minio/backup;
      /usr/bin/mc mb minio/backup;
      /usr/bin/mc policy download minio/backup;
      exit 0;
      "

  mini-backup:
    image: rg.fr-par.scw.cloud/open-mini-backup/mini-backup:latest
    container_name: mini-backup
    restart: always
    volumes:
      - ./config:/app/config
    environment:
      - AUTO_CONFIG=true
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniopassword
      - GO_ENV=dev
      - AES_KEY=582e9ffb85124ee9b8cd572927ef671648e9dedd36f5352f755750930a2248d6
  
  ui-mini-backup:
    image: rg.fr-par.scw.cloud/open-mini-backup/ui-mini-backup:latest
    container_name: ui-mini-backup
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mini-backup
      - ui-mini-backup


  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./mariadb/data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=superdb
      - MARIADB_USER=user
      - MARIADB_PASSWORD=admin

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    # ports:
      # - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
