backups:
  glpi:
    type: mysql
    mysql: 
      databases: [
        "glpidb",
      ]
      host: "localhost"
      port: "3306"
      user: "glpi_user"
      password: "glpi"
      ssl: "false"
    path:
      local: "./backups"
      s3: "backup/glpi-dev/mysql"
    retention:
      standard: 
        days: 1
      glacier:
        days: 365
    schedule:
      standard: "*/2 * * * *"
      glacier: "0 18 * * 5"
  # glpi-file:
  #   type: folder
  #   folder: [
  #     "/home/killian/dev/aidalinfo/backup-tool-go/glpi/data",
  #   ]
  #   path:
  #     local: "./backups"
  #     s3: "backup/glpi-dev/folder"
  #   retention:
  #     standard: 
  #       days: 14
  #   schedule:
  #     standard: "*/60 * * * *"
  #     glacier: "0 18 * * 5"
  # mongo:
  #   type: mongo
  #   mongo: 
  #     host: "localhost"
  #     port: "27018"
  #     user: "root"
  #     password: "example"
  #     ssl: false
  #   path:
  #     local: "./backups"
  #     s3: "backup/mongo/mongo"
  #   retention:
  #     standard: 
  #       days: 14
  #     glacier:
  #       days: 365
  #   schedule:
  #     standard: "*/2 * * * *"