backups:
  sqlserver-01:
    type: mysql
    mysql:
      all: true
      host: "localhost"
      port: "3306"
      user: "root"
      password: "example"
      ssl: "false"
    path:
      local: "./backups"
      s3: "backup/glpi-dev/mysql"
    retention:
      standard: 
        days: 20
    schedule:
      standard: "*/2 * * * *"