server:
  port: 8086
  debug: true
  log: "./logs/server.log"

# secret_manager:
#   infisical:
#     name: "infisical"
#     url: "https://url.fr/"  
#     api_key: "${{INFISICAL_API_KEY}}"  
#     project_id: "${{INFISICAL_PROJECT_ID}}" 
 
rstorage:
  minio:
    endpoint: "http://localhost:9000"
    bucket_name: "backup"
    access_key: "minioadmin"
    secret_key: "miniopassword"
    region: "fr-par"